apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kibana-ip
  labels:
    app: hello
spec:
  backend:
    serviceName: kibana
    servicePort: 5601